sudo: required
services:
  - docker

before_install:
  - docker build -t palo/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run palo/react-test npm test -- --coverage

after_success:
  - docker build -t pablo161/multi-client ./client
  - docker build -t pablo161/multi-nginx ./nginx
  - docker build -t pablo161/multi-server ./server
  - docker build -t pablo161/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push pablo161/multi-client
  - docker push pablo161/multi-nginx
  - docker push pablo161/multi-server
  - docker push pablo161/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-933271683194
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
