sudo: required
services:
  - docker

before_install:
  - docker build -t palo/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run palo/react-test npm test -- --coverage

after_success:
  - docker build -t palo/multi-client ./client
  - docker build -t palo/multi-nginx ./nginx
  - docker build -t palo/multi-server ./server
  - docker build -t palo/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push palo/multi-client
  - docker push palo/multi-nginx
  - docker push palo/multi-server
  - docker push palo/multi-worker
